services:

  postgres:
    container_name: postgres
    image: postgres:14.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    networks:
      - net
    ports:
      - 5433:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d app" ]
      interval: 5s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  redis:
    image: redis
    networks:
      - net
    ports:
      - 6379:6379

  data-generator:
    build: ./generator
    container_name: generator
    networks:
      - net
    depends_on:
      - redis
      - postgres
  
  broadcaster:
    build: ./broadcaster
    container_name: broadcaster
    ports:
      - 5679:5679
    networks:
      - net
    depends_on:
      - redis

  server:
    build: ./server
    container_name: server
    ports:
      - 5000:5000
    networks:
      - net
    depends_on:
      - redis
      - postgres

  dashboard:
    build: ./dashboard
    container_name: dashboard
    ports:
      - "8088:8080"
    networks:
      - net


networks:
  net: